### ISSUE TITLE
[Wallet] Tracking: features at launch

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#609]
## Must be done
* [x] Core: support Identity v5.2 and new relayer
* [ ] Core: support for QuickAccManager
* [ ] WalletConnect: support for connecting, sending transactions, signing - with deep links on desktop
* [ ] UX tweaks: large deposit button instead of separate ones
* [x] #612
* [x] Tx preview: add a transaction preview dialog that lets you choose txn fee (slow, medium, fast); when swapping/diversifying, embed the fee selection in that dialog, don't pop up a new one

## Top priority
* [ ] WALLET token: in the top right, show how much you've earned, plus a button to claim; when clicked, pop up a dialog with a breakdown between liquidity mining/referral/gas rebates/ADX staking
* [ ] Referrals: all the UI has to do is record the code from the URL when sending POST /identity
* [x] Direct Trezor and Ledger support - we already have this, should be easy to enable
* [x] Landing page refresh: tweak content to focus on more important features, token info, remove illustrations
* [ ] Transactions tab showing all outgoing and their status

## Medium priority, low hanging fruit
- [x] Diversify feature: marked as low-hanging cause it's almost ready, should be enabled
- [x] Tx preview: basic parsing/decoding of each transaction
- [x] Authorities tab: easily add/remove authorities (currently called "privileges")
- [ ] Dashboard: show more tokens, vaults support
- [ ] Swap dialog to support custom tokens

## Medium priority
- [x] Multichain: Polygon support, "zero fee transactions"
- [ ] Multichain: auto chain switching; if we receive a request from WalletConnect to switch the chain, we should just do it right away if we support that chain; if not, show an error, or just switch to it and disable most features
- [ ] Tx preview: show net worth estimation before and after the txn; show a detailed breakdown of all transfers
- [ ] WalletConnect: "Connected dApps" tab where you can disconnect each one individually; should have a text input field ot quickly search through them
- [ ] WalletConnect: EIP712 support: https://gist.github.com/danfinlay/750ce1e165a75e1c3387ec38cf452b71
- [ ] WalletConnect: sign transactions (EIP 1271); keep in mind the `Identity` needs to be deployed before we can do that
- [ ] Transactions tab: ability to speed up transactions (replace txn with a given nonce with the relayer)
- [ ] Relayer: email confirmations for transactions 
- [ ] Web notifications for mined txns
- [ ] UX: product tour/walkthrough

## Benched for later
- [ ] Multi-account: ability to switch between accounts
- [ ] Multi-account: passthrough mode: ability to use an underlying keypair directly; all "smart" features disabled in this mode
- [ ] Multi-chain: Arbitrum and Fantom
- [ ] ENS, with central registry to reserve a name w/o gas
- [ ] Token lists

**Comment by Ivshti** [comment]
New repo version:


## Must be done
* [x] Core: support Identity v5.2 and new relayer
* [x] Core: support for QuickAccManager
* [x] WalletConnect: support for connecting, sending transactions, signing - with deep links on desktop
* [ ] UX tweaks: large deposit button instead of separate ones
* [x] #612
* [x] Tx preview: add a transaction preview dialog that lets you choose txn fee (slow, medium, fast); when swapping/diversifying, embed the fee selection in that dialog, don't pop up a new one

## Top priority
* [ ] WALLET token: in the top right, show how much you've earned, plus a button to claim; when clicked, pop up a dialog with a breakdown between liquidity mining/referral/gas rebates/ADX staking
* [ ] Referrals: all the UI has to do is record the code from the URL when sending POST /identity
* [x] Direct Trezor and Ledger support - we already have this, should be easy to enable
* [x] Landing page refresh: tweak content to focus on more important features, token info, remove illustrations
* [x] Transactions tab showing all outgoing and their status

## Medium priority, low hanging fruit
- [ ] Diversify feature: marked as low-hanging cause it's almost ready, should be enabled
- [x] Tx preview: basic parsing/decoding of each transaction
- [x] Authorities tab: easily add/remove authorities (currently called "privileges")
- [x] Dashboard: show more tokens, vaults support
- [ ] Swap dialog to support custom tokens

## Medium priority
- [x] Multichain: Polygon support, "zero fee transactions"
- [ ] Multichain: auto chain switching; if we receive a request from WalletConnect to switch the chain, we should just do it right away if we support that chain; if not, show an error, or just switch to it and disable most features
- [ ] Tx preview: show net worth estimation before and after the txn; show a detailed breakdown of all transfers
- [x] WalletConnect: "Connected dApps" tab where you can disconnect each one individually; should have a text input field ot quickly search through them
- [ ] WalletConnect: EIP712 support: https://gist.github.com/danfinlay/750ce1e165a75e1c3387ec38cf452b71
- [ ] WalletConnect: sign transactions (EIP 1271); keep in mind the `Identity` needs to be deployed before we can do that
- [ ] Transactions tab: ability to speed up transactions (replace txn with a given nonce with the relayer)
- [x] Relayer: email confirmations for transactions 
- [ ] Web notifications for mined txns
- [ ] UX: product tour/walkthrough

## Benched for later
- [x] Multi-account: ability to switch between accounts
- [ ] Multi-account: passthrough mode: ability to use an underlying keypair directly; all "smart" features disabled in this mode
- [ ] Multi-chain: Arbitrum and Fantom
- [ ] ENS, with central registry to reserve a name w/o gas
- [ ] Token lists

Closing, will track those in separate issues from now on
